apiVersion: apps/v1
kind: Deployment
metadata:
  name: rajini-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rajini
      version: green
  template:
    metadata:
      labels:
        app: rajini
        version: green
    spec:
      containers:
      - name: rajini
        image: <your-dockerhub-username>/rajini-app:<tag>
        ports:
        - containerPort: 8080

